# **Cheminformatis Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)**

Zeinab Alaa

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:
* Redundant code cells were deleted.
* Code cells for saving files to Google Drive has been deleted.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.0-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.7 MB/s eta 0:00:00
Downloading requests_cache-1.3.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 3.0 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 2.2 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.3.0 url-normalize-2.2.1

## **Importing libraries**

In [2]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for Epidermal Growth Factor**

In [3]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('epidermal growth factor')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Pro-epidermal growth factor,34.0,False,CHEMBL5734,"[{'accession': 'P01133', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Mus musculus,Epidermal growth factor receptor,29.0,False,CHEMBL3608,"[{'accession': 'Q01279', 'component_descriptio...",SINGLE PROTEIN,10090
2,[],Homo sapiens,Growth factor receptor-bound protein 7,27.0,False,CHEMBL1649051,"[{'accession': 'Q14451', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Delta and Notch-like epidermal growth factor-r...,27.0,False,CHEMBL5291567,"[{'accession': 'Q8NFT8', 'component_descriptio...",SINGLE PROTEIN,9606
4,[],Homo sapiens,Epidermal growth factor receptor,25.0,False,CHEMBL203,"[{'accession': 'P00533', 'component_descriptio...",SINGLE PROTEIN,9606
...,...,...,...,...,...,...,...,...,...
1632,[],Homo sapiens,Mitochondrial complex I (NADH dehydrogenase),0.0,False,CHEMBL2363065,"[{'accession': 'P03923', 'component_descriptio...",PROTEIN COMPLEX,9606
1633,[],Homo sapiens,26S proteasome,0.0,False,CHEMBL2364701,"[{'accession': 'Q99460', 'component_descriptio...",PROTEIN COMPLEX,9606
1634,[],Homo sapiens,Caspase,0.0,False,CHEMBL3831289,"[{'accession': 'P49662', 'component_descriptio...",PROTEIN FAMILY,9606
1635,[],Homo sapiens,80S Ribosome,0.0,False,CHEMBL3987582,"[{'accession': 'P08865', 'component_descriptio...",PROTEIN NUCLEIC-ACID COMPLEX,9606
1636,[],Homo sapiens,Cytochrome P450,0.0,False,CHEMBL4523986,"[{'accession': 'P08684', 'component_descriptio...",PROTEIN FAMILY,9606

### **Select and retrieve bioactivity data for *Human Acetylcholinesterase* (first entry)**

We will assign the fifth entry (which corresponds to the target protein, *Epidermal Growth Factor*) to the ***selected_target*** variable

In [4]:
selected_target = targets.target_chembl_id[1]
selected_target

'CHEMBL3608'

Here, we will retrieve only bioactivity data for *Epidermal Growth Factor* (CHEMBL3608) that are reported as pChEMBL values.

In [5]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [6]:
df = pd.DataFrame.from_dict(res)

In [7]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,110221,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
1,None,None,113118,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,119387,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,133319,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,25.0
4,None,None,193384,[],CHEMBL675513,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26021878,[],CHEMBL5580384,Inhibition of recombinant mouse EGFR by ELISA,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,3.5
93,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239137,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,5.8
94,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239138,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,14.4
95,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239139,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,19.3
96,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239140,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,1.6

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [21]:
df.to_csv('EpidermalGrowthFactor_01_bioactivity_data_raw.csv', index=False)

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [9]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipython-input-3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,110221,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
1,None,None,113118,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,119387,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,133319,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,25.0
4,None,None,193384,[],CHEMBL675513,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26021878,[],CHEMBL5580384,Inhibition of recombinant mouse EGFR by ELISA,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,3.5
93,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239137,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,5.8
94,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239138,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,14.4
95,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239139,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,19.3
96,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239140,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,1.6

In [10]:
len(df2.canonical_smiles.unique())

91

In [11]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,110221,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
1,None,None,113118,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,119387,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,133319,[],CHEMBL675511,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,25.0
4,None,None,193384,[],CHEMBL675513,Inhibition of epidermal growth factor receptor...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26021877,[],CHEMBL5580384,Inhibition of recombinant mouse EGFR by ELISA,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,1.7
92,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26021878,[],CHEMBL5580384,Inhibition of recombinant mouse EGFR by ELISA,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,uM,UO_0000065,None,3.5
94,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239138,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,14.4
95,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239139,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,19.3
96,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26239140,[],CHEMBL5663121,Inhibition of EGFR expressed in mouse NIH3T3 c...,B,None,None,BAO_0000190,...,Mus musculus,Epidermal growth factor receptor,10090,None,None,IC50,nmol/L,UO_0000065,None,1.6

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [12]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL292323,COc1cccc2c(C(=O)Nc3ccccc3)c(SSc3c(C(=O)Nc4cccc...,100000.0
1,CHEMBL304414,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3ccccc3n2C)c(C(=O)N...,100000.0
2,CHEMBL62176,CN1C(=S)C(C(=O)Nc2ccccc2)c2ccccc21,100000.0
3,CHEMBL62701,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3cccnc3n2C)c(C(=O)N...,25000.0
4,CHEMBL137617,C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1,70.0
...,...,...,...
91,CHEMBL5593705,CS(=O)(=O)c1ccc(NC(=O)c2cc(-c3ccc(Cl)cc3)n(-c3...,1700.0
92,CHEMBL1336,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,3500.0
94,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,14.4
95,CHEMBL553,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,19.3
96,CHEMBL545315,C=CC(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1OCCCN...,1.6

Saves dataframe to CSV file

In [14]:
df3.to_csv('EpidermalGrowthFactor_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [15]:
df4 = pd.read_csv('EpidermalGrowthFactor_02_bioactivity_data_preprocessed.csv')

In [16]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [17]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL292323,COc1cccc2c(C(=O)Nc3ccccc3)c(SSc3c(C(=O)Nc4cccc...,100000.0,inactive
1,CHEMBL304414,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3ccccc3n2C)c(C(=O)N...,100000.0,inactive
2,CHEMBL62176,CN1C(=S)C(C(=O)Nc2ccccc2)c2ccccc21,100000.0,inactive
3,CHEMBL62701,Cn1c(SSc2c(C(=O)Nc3ccccc3)c3cccnc3n2C)c(C(=O)N...,25000.0,inactive
4,CHEMBL137617,C/N=N/Nc1ccc2ncnc(Nc3cccc(Br)c3)c2c1,70.0,active
...,...,...,...,...
86,CHEMBL5593705,CS(=O)(=O)c1ccc(NC(=O)c2cc(-c3ccc(Cl)cc3)n(-c3...,1700.0,intermediate
87,CHEMBL1336,CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(C(F)(F)F)...,3500.0,intermediate
88,CHEMBL939,COc1cc2ncnc(Nc3ccc(F)c(Cl)c3)c2cc1OCCCN1CCOCC1,14.4,active
89,CHEMBL553,C#Cc1cccc(Nc2ncnc3cc(OCCOC)c(OCCOC)cc23)c1,19.3,active
90,CHEMBL545315,C=CC(=O)Nc1cc2c(Nc3ccc(F)c(Cl)c3)ncnc2cc1OCCCN...,1.6,active

Saves dataframe to CSV file

In [18]:
df5.to_csv('EpidermalGrowthFactor_03_bioactivity_data_curated.csv', index=False)

In [19]:
! zip EpidermalGrowthFactor.zip *.csv

  adding: epidermalgrowthfactor_01_bioactivity_data_raw.csv (deflated 89%)
  adding: Epidermal Growth Factor_02_bioactivity_data_preprocessed.csv (deflated 73%)
  adding: EpidermalGrowthFactor_02_bioactivity_data_preprocessed.csv (deflated 73%)
  adding: EpidermalGrowthFactor_03_bioactivity_data_curated.csv (deflated 75%)

In [20]:
! ls -l

total 100
-rw-r--r-- 1 root root 57149 Feb 14 22:12  epidermalgrowthfactor_01_bioactivity_data_raw.csv
-rw-r--r-- 1 root root  6197 Feb 14 22:13 'Epidermal Growth Factor_02_bioactivity_data_preprocessed.csv'
-rw-r--r-- 1 root root  6197 Feb 14 22:14  EpidermalGrowthFactor_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 root root  7022 Feb 14 22:15  EpidermalGrowthFactor_03_bioactivity_data_curated.csv
-rw-r--r-- 1 root root 12585 Feb 14 22:15  EpidermalGrowthFactor.zip
drwxr-xr-x 1 root root  4096 Jan 16 14:24  sample_data

---